#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ndpi
Version  : 3.0
Release  : 14
URL      : https://github.com/ntop/nDPI/archive/3.0.tar.gz
Source0  : https://github.com/ntop/nDPI/archive/3.0.tar.gz
Summary  : deep packet inspection library
Group    : Development/Tools
License  : GPL-2.0 LGPL-3.0
Requires: ndpi-bin = %{version}-%{release}
Requires: ndpi-lib = %{version}-%{release}
Requires: ndpi-license = %{version}-%{release}
BuildRequires : libpcap-dev
BuildRequires : numactl-dev
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libhs)
Patch1: 0001-Fix-library-install-location.patch

%description
This direcgory contains the Python bindings for nDPI
Usage:
- python3 ndpi_example.py <interface>
- python3 ndpi_example.py <pcap_file>

%package bin
Summary: bin components for the ndpi package.
Group: Binaries
Requires: ndpi-license = %{version}-%{release}

%description bin
bin components for the ndpi package.


%package dev
Summary: dev components for the ndpi package.
Group: Development
Requires: ndpi-lib = %{version}-%{release}
Requires: ndpi-bin = %{version}-%{release}
Provides: ndpi-devel = %{version}-%{release}
Requires: ndpi = %{version}-%{release}

%description dev
dev components for the ndpi package.


%package lib
Summary: lib components for the ndpi package.
Group: Libraries
Requires: ndpi-license = %{version}-%{release}

%description lib
lib components for the ndpi package.


%package license
Summary: license components for the ndpi package.
Group: Default

%description license
license components for the ndpi package.


%prep
%setup -q -n nDPI-3.0
cd %{_builddir}/nDPI-3.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580840438
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1580840438
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ndpi
cp %{_builddir}/nDPI-3.0/COPYING %{buildroot}/usr/share/package-licenses/ndpi/e203d4ef09d404fa5c03cf6590e44231665be689
cp %{_builddir}/nDPI-3.0/packages/ubuntu/debian/COPYRIGHT %{buildroot}/usr/share/package-licenses/ndpi/dfac199a7539a404407098a2541b9482279f690d
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/ndpi/ndpiCustomCategory.txt
rm -f %{buildroot}/usr/bin/ndpi/ndpiProtos.txt

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ndpiReader

%files dev
%defattr(-,root,root,-)
/usr/include/ndpi/ndpi_api.h
/usr/include/ndpi/ndpi_classify.h
/usr/include/ndpi/ndpi_config.h
/usr/include/ndpi/ndpi_define.h
/usr/include/ndpi/ndpi_includes.h
/usr/include/ndpi/ndpi_main.h
/usr/include/ndpi/ndpi_protocol_ids.h
/usr/include/ndpi/ndpi_protocols.h
/usr/include/ndpi/ndpi_typedefs.h
/usr/include/ndpi/ndpi_unix.h
/usr/include/ndpi/ndpi_win32.h
/usr/lib64/libndpi.so
/usr/lib64/pkgconfig/libndpi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libndpi.so.3
/usr/lib64/libndpi.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ndpi/dfac199a7539a404407098a2541b9482279f690d
/usr/share/package-licenses/ndpi/e203d4ef09d404fa5c03cf6590e44231665be689
