#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ndpi
Version  : 2.6
Release  : 11
URL      : https://github.com/ntop/nDPI/archive/2.6.tar.gz
Source0  : https://github.com/ntop/nDPI/archive/2.6.tar.gz
Summary  : deep packet inspection library
Group    : Development/Tools
License  : GPL-2.0 LGPL-3.0
Requires: ndpi-bin = %{version}-%{release}
Requires: ndpi-lib = %{version}-%{release}
Requires: ndpi-license = %{version}-%{release}
BuildRequires : libpcap-dev
Patch1: 0001-Fix-installation-locations.patch

%description
This directory contains the files needed to build the package
named 'ndpi' for the Debian GNU/Linux distribution.

%package bin
Summary: bin components for the ndpi package.
Group: Binaries
Requires: ndpi-license = %{version}-%{release}

%description bin
bin components for the ndpi package.


%package dev
Summary: dev components for the ndpi package.
Group: Development
Requires: ndpi-lib = %{version}-%{release}
Requires: ndpi-bin = %{version}-%{release}
Provides: ndpi-devel = %{version}-%{release}

%description dev
dev components for the ndpi package.


%package lib
Summary: lib components for the ndpi package.
Group: Libraries
Requires: ndpi-license = %{version}-%{release}

%description lib
lib components for the ndpi package.


%package license
Summary: license components for the ndpi package.
Group: Default

%description license
license components for the ndpi package.


%prep
%setup -q -n nDPI-2.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553798599
export LDFLAGS="${LDFLAGS} -fno-lto"
%autogen --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1553798599
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ndpi
cp COPYING %{buildroot}/usr/share/package-licenses/ndpi/COPYING
cp packages/ubuntu/debian/COPYRIGHT %{buildroot}/usr/share/package-licenses/ndpi/packages_ubuntu_debian_COPYRIGHT
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ndpiReader

%files dev
%defattr(-,root,root,-)
/usr/include/ndpi/ndpi_api.h
/usr/include/ndpi/ndpi_config.h
/usr/include/ndpi/ndpi_define.h
/usr/include/ndpi/ndpi_includes.h
/usr/include/ndpi/ndpi_main.h
/usr/include/ndpi/ndpi_protocol_ids.h
/usr/include/ndpi/ndpi_protocols.h
/usr/include/ndpi/ndpi_typedefs.h
/usr/include/ndpi/ndpi_unix.h
/usr/include/ndpi/ndpi_win32.h
/usr/lib64/libndpi.so
/usr/lib64/pkgconfig/libndpi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libndpi.so.2
/usr/lib64/libndpi.so.2.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ndpi/COPYING
/usr/share/package-licenses/ndpi/packages_ubuntu_debian_COPYRIGHT
